play : target0 target1 target2 target3

target0 : play_again0.c
	gcc -o play_again0.o play_again0.c
target1 : play_again1.c
	gcc -o play_again1.o play_again1.c
target2 : play_again2.c
	gcc -o play_again2.o play_again2.c
target3 : play_again3.c
	gcc -o play_again3.o play_again3.c

clean:
	rm -f play_again*.o



